### ISSUE TITLE
New cache database structure

### ISSUE THREAD

**Issue by AndreKR** [coblo/gui-demo#111]
Proposed cache mechanism:

![image](https://user-images.githubusercontent.com/1188538/33445550-773baec8-d5fd-11e7-91f7-8883781251df.png)

Synchronization (on startup or when a new block arrives):
1. `offset` = 0
2. SELECT * FROM blocks ORDER BY height DESC LIMIT 1 OFFSET `offset`
3. Get block with this height from Node, check if hash is identical to database
4. If not identical, increment `offset` and repeat from step 2
5. If matching block is found, then cascading DELETE FROM blocks WHERE height > `height of matching block`
6. Ask Node for all blocks between `height of matching block` and the height that is returned by API call `getblockcount`
7. Parse these blocks, extract data into database as needed

**Comment by Swarlston** [comment]
We should add the block time, I think

**Comment by Patricia92** [comment]
And we should add an table with all permissions and maybe another table with all pending votes.
We could update this tables every time, the "Vote" table has an update.

**Comment by titusz** [comment]
Instead of Alias and Timestamp tables we could use a generic Stream table with a stream_id field.

**Comment by Patricia92** [comment]
We thought about it and decided against one table for all streams.
We do not want to force every user to save every stream, so we only save the streams the user has subscribed to and add a table for every subscribed stream. It's more practicable like this.

**Comment by Patricia92** [comment]
![image](https://user-images.githubusercontent.com/11156851/33554431-fb851654-d8fc-11e7-9f89-3c18d05ab63e.png)
