### ISSUE TITLE
Windows scaling destroys layout.

### ISSUE THREAD

**Issue by titusz** [coblo/gui-demo#114]
With HiDPI Displays Windows is usually set to higher scaling to keep text and gui elements at a reasonable size. This is how the wizard looks at 150% scaling on windows 10:
![image](https://user-images.githubusercontent.com/278556/34210171-32b1e608-e595-11e7-8e99-0952fe0020c6.png)

**Comment by titusz** [comment]
See also: 
http://doc.qt.io/qt-5/highdpi.html
http://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization/

**Comment by Patricia92** [comment]
Should be fixed analog to https://github.com/coblo/gui-demo/commit/ac5cf5428615b312964435da675077e0e3f3e32d

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/commit/7c6fdda8187c50164097bf1b6889434149a7956b
