### ISSUE TITLE
Handle 0 balance cases

### ISSUE THREAD

**Issue by Patricia92** [coblo/gui-demo#117]
The setup wizard gives information to the user how to get some initial coins for testing. For cases where the user ignored this information during setup, we should also give such notice in the main application screen if the balance is 0.

**Comment by titusz** [comment]
The setup wizard gives information to the user how to get some initial coins for testing. For cases where the user ignored this information during setup, we should also give such notice in the main application screen if the balance is 0.

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/pull/131
