### ISSUE TITLE
Balance formatting is note locale independent

### ISSUE THREAD

**Issue by titusz** [coblo/gui-demo#122]
Reproduce by setting `locale.setlocale(locale.LC_ALL, 'English')` (on windows) in `Application.__init__`. and see how balance is formatted in the GUI:
![image](https://user-images.githubusercontent.com/278556/35184343-934aff50-fdf4-11e7-8135-4ae247ed921a.png)

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/commit/37767a3c5dd5beb38efecc08a86d25699a2d510c
