### ISSUE TITLE
Add support for public transaction comments

### ISSUE THREAD

**Issue by Patricia92** [coblo/gui-demo#125]

**Comment by Patricia92** [comment]
Comments as JSON without stream as direct transaction metadata.

**Comment by titusz** [comment]
Lets add some choices to the GUI comment field. At current state choices would be: `Local` or `Public`.
Local will store the comment only in the nodes wallet db. We would do this with a simple
`send(address, amount, [comment])` api call. `Public` would use the transaction metadata with a
`sendwithdata(addess, amount, object)` with *object* looking like this:

```
{
    "json": { "comment": "my comment"}
}
```
We should also define and check for a sensible allowed limit of comment length and character set that applications must support. How about we stick with [SEPA](https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/sepa-verwendungszweck/) specs and ensure that our on-chain transaction comments are compatible with legacy banking applications :)

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/tree/public_comments

Comment length is limited to 100 because the QLineEdit has maxLength of 100
