### ISSUE TITLE
Wizard crashes when syncing database

### ISSUE THREAD

**Issue by Patricia92** [coblo/gui-demo#144]
No visible output, that an error occured. Just a debug message. Restarting solves the problem.

Error message: raised as a result of Query-invoked autoflush;

**Comment by Patricia92** [comment]
Error Mesage:
sync:(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO blocks (hash, mining_time, height) VALUES (?, ?, ?)'] [parameters: (<memory at 0x0000000005F1F888>, '2018-02-21 11:20:45.000000', 0)]

**Comment by AndreKR** [comment]
I'll have a look at this later today.

**Comment by AndreKR** [comment]
@Patricia92 I can't reproduce it anymore. We have to look on your machine again.

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/commit/9af12ac7421f4c2de0779d9c9198750a1a55ff7e

This is a hotfix, we still have to find a correct solution

**Comment by AndreKR** [comment]
What didn't work: Introducing a copy of `data_session_scope()` that returns a different SQLAlchemy session. I tried that because I read that you shouldn't use the same connect from two different threads (which apparently we don't do, because check_same_thread is True and we don't get a warning).
