### ISSUE TITLE
Less obstrusive notifications

### ISSUE THREAD

**Issue by titusz** [coblo/gui-demo#153]
Transaction notifications on the buttom of the GUI are red. This is a bit alienating as the message is not an error. We should use a more unobstrusive color like blue ...

**Comment by Patricia92** [comment]
![image](https://user-images.githubusercontent.com/11156851/37829772-ae39e5a6-2ea0-11e8-9e3e-78ffd95e27c2.png)

The "you have no coins" warning is now also blue, should we change this?

https://github.com/coblo/gui-demo/commit/872b1f6a8dae73a1b7f57d05b52950ed9b7af447
