### ISSUE TITLE
Pillow dependency failed to install

### ISSUE THREAD

**Issue by albabosh** [coblo/gui-demo#162]
Collecting Pillow==4.3.0
  Using cached https://files.pythonhosted.org/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz
Requirement already satisfied: olefile in c:\users\саша\pycharmprojects\rurtokengui\venv\lib\site-packages (from Pillow==4.3.0) (0.46)
Installing collected packages: Pillow
  Running setup.py install for Pillow: started
    Running setup.py install for Pillow: finished with status 'error'
    Complete output from command C:\Users\Саша\PycharmProjects\rurtokengui\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Саша\\AppData\\Local\\Temp\\pycharm-packaging\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\9FA5~1\AppData\Local\Temp\pip-record-3sc6tu35\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Саша\PycharmProjects\rurtokengui\venv\include\site\python3.7\Pillow:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\version.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_util.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing requirements to Pillow.egg-info\requires.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis\*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "C:\Users\Саша\AppData\Local\Temp\pycharm-packaging\Pillow\setup.py", line 787, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "C:\Users\Саша\PycharmProjects\rurtokengui\venv\lib\site-packages\setuptools-39.1.0-py3.7.egg\setuptools\__init__.py", line 129, in setup
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Саша\PycharmProjects\rurtokengui\venv\lib\site-packages\setuptools-39.1.0-py3.7.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Саша\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Саша\AppData\Local\Temp\pycharm-packaging\Pillow\setup.py", line 577, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Саша\AppData\Local\Temp\pycharm-packaging\Pillow\setup.py", line 799, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------

Command "C:\Users\Саша\PycharmProjects\rurtokengui\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Саша\\AppData\\Local\\Temp\\pycharm-packaging\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\9FA5~1\AppData\Local\Temp\pip-record-3sc6tu35\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Саша\PycharmProjects\rurtokengui\venv\include\site\python3.7\Pillow" failed with error code 1 in C:\Users\Саша\AppData\Local\Temp\pycharm-packaging\Pillow\
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Windows 7 x64, Python 3.7, Pycharm IDE 2018.2.5

**Comment by titusz** [comment]
Your binary extension build environment is not configured to build Pillow 4.3.0. And for Python 3.7 there are no binary wheels for Pillow 4.3.0 on pypi. To fix this you can either switch to Python 3.6 or install `Pillow==5.3.0` which has binary wheels for py3.7.
