### ISSUE TITLE
Total balance and current balance in transaction history don´t match.

### ISSUE THREAD

**Issue by titusz** [coblo/gui-demo#18]
The balance reported by the nodes rpc-api does not match up with the balance calculated by the transaction history. In most cases the rpc reported balance is laging behind by 6 blocks.

**Comment by Swarlston** [comment]
This is probably a problem with multichain, and we're going to ask them for support.

**Comment by Patricia92** [comment]
Should be fixed with https://github.com/coblo/gui-demo/commit/b6d47d35094d84318b2726313a9cef8dd6f1fb77
