### ISSUE TITLE
Transaction list balance ≠ "My Balance"

### ISSUE THREAD

**Issue by dan-ic** [coblo/gui-demo#72]
Transaction list balance / "My balance" mismatch:

![coblo_scr02](https://user-images.githubusercontent.com/33722129/32917325-1dcddd36-cb1f-11e7-99cb-ff549a9e1df3.jpg)

**Comment by oweicker** [comment]
confirm

send coins is also only possible for the funds listed in my balance

**Comment by Patricia92** [comment]
Duplicate Issue:
#18
