### ISSUE TITLE
edit alias icon

### ISSUE THREAD

**Issue by oweicker** [coblo/gui-demo#75]
gear icon makes no sense, default meaning is settings and already used as settings icon.

probably a pencil or something similar should be better fit

**Comment by titusz** [comment]
I´d also say this is positioned to prominently. The user is not expected to change his alias all the time so why bother him with an edit button on the main wallet screen. I think this should be moved to the settings section where we might offer a full "My Account" tab. The user could post an avatar and other information if he likes. This information would also be helpful when evaluating to vote for skills.
