### ISSUE TITLE
notification for functions with delay

### ISSUE THREAD

**Issue by oweicker** [coblo/gui-demo#78]
user unfamiliar with blockchains probably expect instant results after an action ... all actions with delay, eg changing your alias should have a small notification something like "Pending Transaction, it will take 1-2 Minutes until its confirmed in the next block".

Additional in the notice a "never show again" checkbox for more experienced users.

**Comment by titusz** [comment]
Yes this problem will pop up over and over. We should find a generic and user friendly mode of handling the **non immediacy** of actions that require blockchain confirmation. We actually might need 2 notifications per action. First that an action is queued and another one when it has been confirmed. Notifications in the header or footer section of the application would be my first idea. The questions is how many notifications we can show there without cluttering the interface. Maybe we just show them fade in and fade out after a few seconds. Alternatively we could offer a full notification log on a separate screen and an "unread" counter placed globally in the UI. **On the other hand** every action that has a delay for blockchain confirmation will have a corresponding entry in the main transaction history. And the confirmation state is also shown there. So why a separate notification log... I am looking for more suggestions here....

**Comment by titusz** [comment]
how about something like this:
![image](https://user-images.githubusercontent.com/278556/32945267-0acfba82-cb93-11e7-9afd-80a44a398634.png)

**Comment by Patricia92** [comment]
I implemented a possible solution:
https://github.com/coblo/gui-demo/pull/116
