### ISSUE TITLE
limit transaction log

### ISSUE THREAD

**Issue by oweicker** [coblo/gui-demo#81]
show only last 100 (?), then pagination or download as file

**Comment by titusz** [comment]
We could use the QT "Fetch More" pattern: https://doc.qt.io/qt-5/qtwidgets-itemviews-fetchmore-example.html

**Comment by Patricia92** [comment]
Should be solved by https://github.com/coblo/gui-demo/commit/3457fecda69b4af4ceca8ab40f0a083fea09cc98
