### ISSUE TITLE
edit alias keeps unconfirmed in transaction log

### ISSUE THREAD

**Issue by oweicker** [coblo/gui-demo#82]
after changing alias, transaction keeps unconfirmed in transaction log (even 2 blocks later), after restart application correct status is shown

**Comment by titusz** [comment]
Yes i have noticed this too. It looks like the confirmation status is not synchronized on transaction table updates.

**Comment by Patricia92** [comment]
https://github.com/coblo/gui-demo/commit/e4c3614c8d32be22870b2d617bf86cd2d08dc67a
